#!/usr/bin/env python3
"""
PowerBI Configuration Setup for Auê Natural
Interactive script to configure PowerBI credentials for automatic dashboard updates
"""

import os
import sys
from pathlib import Path

def create_env_file():
    """Create or update .env file with PowerBI credentials."""
    print("🔧 PowerBI Configuration Setup")
    print("=" * 50)
    
    env_file = Path(".env")
    
    # Read existing .env if it exists
    existing_config = {}
    if env_file.exists():
        with open(env_file) as f:
            for line in f:
                if "=" in line and not line.startswith("#"):
                    key, value = line.strip().split("=", 1)
                    existing_config[key] = value
    
    print("\nTo get these credentials:")
    print("1. Go to https://app.powerbi.com/")
    print("2. Go to Settings > Admin Portal > App registrations")
    print("3. Create/configure your app for API access")
    print("4. Get workspace and dataset IDs from your dashboard URLs")
    print()
    
    # Collect credentials
    config = {}
    
    config['POWERBI_WORKSPACE_ID'] = input(f"PowerBI Workspace ID [{existing_config.get('POWERBI_WORKSPACE_ID', '')}]: ").strip() or existing_config.get('POWERBI_WORKSPACE_ID', '')
    config['POWERBI_DATASET_ID'] = input(f"PowerBI Dataset ID [{existing_config.get('POWERBI_DATASET_ID', '')}]: ").strip() or existing_config.get('POWERBI_DATASET_ID', '')
    config['POWERBI_CLIENT_ID'] = input(f"PowerBI Client ID [{existing_config.get('POWERBI_CLIENT_ID', '')}]: ").strip() or existing_config.get('POWERBI_CLIENT_ID', '')
    config['POWERBI_CLIENT_SECRET'] = input(f"PowerBI Client Secret [{existing_config.get('POWERBI_CLIENT_SECRET', '')}]: ").strip() or existing_config.get('POWERBI_CLIENT_SECRET', '')
    config['POWERBI_TENANT_ID'] = input(f"PowerBI Tenant ID [{existing_config.get('POWERBI_TENANT_ID', '')}]: ").strip() or existing_config.get('POWERBI_TENANT_ID', '')
    
    # Check if user wants to enable
    enable = input("\nEnable PowerBI auto-updates? (y/N): ").lower().strip()
    config['POWERBI_ENABLED'] = 'true' if enable == 'y' else 'false'
    
    # Write .env file
    with open(env_file, 'w') as f:
        f.write("# Auê Natural - PowerBI Integration Configuration\n")
        f.write("# Generated by setup_powerbi.py\n\n")
        
        f.write("# PowerBI Integration Settings\n")
        f.write(f"POWERBI_ENABLED={config['POWERBI_ENABLED']}\n\n")
        
        f.write("# PowerBI Service Credentials\n")
        f.write(f"POWERBI_WORKSPACE_ID={config['POWERBI_WORKSPACE_ID']}\n")
        f.write(f"POWERBI_DATASET_ID={config['POWERBI_DATASET_ID']}\n")
        f.write(f"POWERBI_CLIENT_ID={config['POWERBI_CLIENT_ID']}\n")
        f.write(f"POWERBI_CLIENT_SECRET={config['POWERBI_CLIENT_SECRET']}\n")
        f.write(f"POWERBI_TENANT_ID={config['POWERBI_TENANT_ID']}\n\n")
        
        f.write("# Notification Settings\n")
        f.write("POWERBI_NOTIFY_EMAIL=true\n")
        f.write("POWERBI_NOTIFY_TEAMS=false\n")
    
    print(f"\n✅ Configuration saved to {env_file}")
    
    if config['POWERBI_ENABLED'] == 'true':
        print("🎉 PowerBI auto-updates ENABLED!")
        print("   Dashboards will update automatically after each data run")
    else:
        print("ℹ️ PowerBI auto-updates disabled")
        print("   You can manually refresh dashboards using files in ./powerbi_data/")

def test_connection():
    """Test PowerBI connection."""
    print("\n🧪 Testing PowerBI connection...")
    
    try:
        # Load environment
        env_file = Path(".env")
        if not env_file.exists():
            print("❌ No .env file found. Run configuration first.")
            return
            
        with open(env_file) as f:
            for line in f:
                if "=" in line and not line.startswith("#"):
                    key, value = line.strip().split("=", 1)
                    os.environ[key] = value
        
        # Import and test
        sys.path.insert(0, 'scripts')
        try:
            from powerbi_auto_update import PowerBIAutoUpdater
        except ImportError:
            print("❌ PowerBI auto-update script not found")
            return False
        
        updater = PowerBIAutoUpdater()
        token = updater.get_access_token()
        
        if token:
            print("✅ PowerBI connection successful!")
            return True
        else:
            print("❌ PowerBI connection failed")
            return False
            
    except Exception as e:
        print(f"❌ Connection test failed: {e}")
        return False

def main():
    """Main setup flow."""
    print("🏪 AUÊ NATURAL - PowerBI Setup")
    print("Automatic Dashboard Updates Configuration")
    print("=" * 50)
    
    while True:
        print("\nOptions:")
        print("1. Configure PowerBI credentials")
        print("2. Test PowerBI connection")
        print("3. View current configuration") 
        print("4. Exit")
        
        choice = input("\nSelect option (1-4): ").strip()
        
        if choice == '1':
            create_env_file()
        elif choice == '2':
            test_connection()
        elif choice == '3':
            env_file = Path(".env")
            if env_file.exists():
                print("\n📄 Current configuration:")
                with open(env_file) as f:
                    for line in f:
                        if not line.startswith("#") and "=" in line:
                            key, value = line.strip().split("=", 1)
                            if "SECRET" in key:
                                value = "*" * len(value)  # Hide secrets
                            print(f"   {key}: {value}")
            else:
                print("❌ No configuration found")
        elif choice == '4':
            break
        else:
            print("Invalid option")
    
    print("\n👋 Setup complete!")
    print("💡 Run 'python run_complete_pipeline.py' to start the full pipeline")

if __name__ == "__main__":
    main()
